### ISSUE TITLE
QR Code Reader

### ISSUE THREAD

**Issue by jubear720** [jbrackins/C-Crypts#5]
# Operations
- Scan QR code
- Send public key (QR code message) to #4 (Authentication Server).

This will most likely be an adaptation of the python scripts I've done for SPACT to take a picture using a USB camera and decoding the QR info.

Slight modifications due to the fact that my SPACT code handles using the proprietary Pi camera, and this project will use the USB camera.

**Comment by SamuelCarroll** [comment]
I have this 'finished' we might want to implement our own qr reader later though.
